from pathlib import Path
from typing import Protocol

from PySide6.QtCore import SignalInstance


class AudioBackend(Protocol):
    """Contrato mínimo usado pelo PlaybackController para controlar o áudio."""

    position_changed: SignalInstance
    duration_changed: SignalInstance
    playback_started: SignalInstance
    playback_paused: SignalInstance
    playback_stopped: SignalInstance
    playback_finished: SignalInstance

    def load(self, path: Path | str) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def set_position(self, position: int) -> None: ...
    def set_volume(self, volume: int | float) -> None: ...
    def output_devices(self): ...
    def output_device_id(self) -> str: ...
    def set_output_device(self, device_id: str) -> bool: ...
    def set_configured_output_device_id(self, device_id: str) -> None: ...
    def set_mono_enabled(self, enabled: bool) -> None: ...
    def mono_enabled(self) -> bool: ...
    def position(self) -> int: ...
    def duration(self) -> int: ...
    def is_playing(self) -> bool: ...
